### PR TITLE
Added KeyCloak setup example yaml files for KKP

### PR DESCRIPTION
**Pull request by archups**
Signed-off-by: archups <archupsawant@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by toschneck** [comment]
Looks good, but please:
- move it to the https://github.com/kubermatic/community-components/tree/master/components/id-management section there we already had some examples
- add the component to main `README.md`

**Comment by archups** [comment]
@toschneck done! adapted as per review comments. Please review and merge. Thanks!

**Comment by archups** [comment]
Hey @toschneck  this is ready for review and merge, please check!

**Pull request merged**
