### PR TITLE
KKP Application for HiveMQ operator

### PR DESCRIPTION
**Pull request by hc2p**
**What this PR does / why we need it**:
This adds a KKP Application to install the HiveMQ operator helm-chart and via it a HiveMQ cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by toschneck** [comment]
@hc2p  could you please add the app to the https://github.com/kubermatic/community-components#kubermatic-applications

**Comment by hc2p** [comment]
@toschneck done

**Review by toschneck — APPROVED** [review]
/approve

**Review by toschneck — APPROVED** [review]

**Pull request merged**
