### PR TITLE
add option to use ssh repos too

### PR DESCRIPTION
**Pull request by jograb**
Signed-off-by: Johann Grabmann <johann@grabmann.eu>

**What this PR does / why we need it**:
Added an option to also use SSH-Repos with an SSH private Key instead of HTTP(S) with username and password

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by dakraus** [comment]
@jograb thank you for submitting this pull request. I tested your changes and configured the addon to clone the repository via SSH. However this resulted in the following error: "ssh: handshake failed: knownhosts: key is unknown", because ArgoCD by default verifies the server's SSH host key.

As outlined in the [ArgoCD documentation](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#unknown-ssh-hosts) we have two possibilities to resolve this issue:
1. We add the field `insecure: true` to the secret containing the repository configuration in order to disable the verification of the server's SSH host key - however this might not be desirable by default
2. We add the possibility to the AddonConfig for the user to provide an initial set of SSH known host entries

Option # 2 is unfortunately not that straightforward to implement: as mentioned in the [ArgoCD documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#quick-reference) 
> for each specific kind of ConfigMap and Secret resource, there is only a single supported resource name (as listed in the above table) - if you need to merge things you need to do it before creating them.

That means we either create and manage the ConfigMap 'argocd-ssh-known-hosts-cm.yaml' exclusively as part of the addon (because the addon reconciliation mechanism would override all external changes) and loose the possibility to dynamically add/remove SSH known host entries via kubectl/argocd CLI or ArgoCD UI. Or we implement some kind of functionality (eventually as initContainer) to ensure the SSH known host entries provided by the user are added to the ConfigMap.

Which option would fit your use case the best?

**Comment by jograb** [comment]
Hi @dakraus, in our setup we already create a own ConfigMap `app.kubernetes.io/name: argocd-ssh-known-hosts-cm` with the `ssh_known_hosts` which contains our internal git as a default value.

For us, this is fine. :) imo option 2 would be the "better" option for most other users, even if this would still involve further effort.

**Comment by dakraus** [comment]
@jograb good to know. Just out of curiosity: how do you create/manage the ConfigMap? As additional KKP addon, as plain YAML manifest, ...?

I will try to find a solution to manage the SSH known host entries as part of the addon as well as dynamically via kubectl/ArgoCD.

**Comment by jograb** [comment]
@dakraus since the entries are always the same for us, as static YAML.

**Comment by dakraus** [comment]
@jograb Thank you for your answer. I will implement the additional functionality to provide an initial set of SSH known host entries and extend this pull request.

**Comment by dakraus** [comment]
@jograb I incorporated your commit into pull request #48 and included the necessary changes to provide an initial set of SSH known host entries.

**Comment by dakraus** [comment]
@jograb your changes were merged. Thank you for your contribution.

**Pull request merged**
