### PR TITLE
Added custom application definition for Canal setup

### PR DESCRIPTION
**Pull request by archups**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

Closes https://github.com/kubermatic-customer/wipro-ces/issues/25

### CODE REVIEW

**Comment by toschneck** [comment]
@archups could you test if it is possible to keep the ``{{  }}`` templates from the standard addon. So if people configure in example the pod cidr the values will get respected.  Just as example https://github.com/kubermatic/kubermatic/blob/main/addons/canal/canal_v3.23.yaml#L4499 this get rendered from the UI values if you create a cluster.

**Comment by archups** [comment]
> @archups could you test if it is possible to keep the `{{ }}` templates from the standard addon. So if people configure in example the pod cidr the values will get respected. Just as example https://github.com/kubermatic/kubermatic/blob/main/addons/canal/canal_v3.23.yaml#L4499 this get rendered from the UI values if you create a cluster.

Sure @toschneck I will test that for few `{{ }}` I was getting error so I had to cleanup those from the yaml. I will revalidate it again to retain as much as possible.

**Comment by archups** [comment]
hey @toschneck I have kept `{{ }}` templates as from standard addon with modification for picking the values from values.yaml. Validated and working as expected. Please review it if this looks fine now.

**Pull request merged**
