### PR TITLE
added new metallb addon manifests v0.13.3

### PR DESCRIPTION
**Pull request by adeniyistephen**
**What this PR does / why we need it**:
Adding new MetalLB manifest to the custom-addons

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes: NONE, new update.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by toschneck** [comment]
@adeniyistephen  I don't think we need this anymore, as it's included in the defaullt addons or?
https://github.com/kubermatic/kubermatic/tree/master/addons/metallb

**Comment by adeniyistephen** [comment]
Yes, it's now part of it.

**Pull request closed without merging**
